name             'goenv-cookbook'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures goenv-cookbook'
long_description 'Installs/Configures goenv-cookbook'
version          '0.1.0'

depends 'apt',             '~> 2.7.0'
depends 'build-essential', '~> 2.2.2'
depends 'git',             '~> 4.1.0'
depends 'ohai',            '>= 1.1'
